# Generated by Django 5.0.3 on 2024-03-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lawyer",
            name="successful_cases",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="lawyer",
            name="unsuccessful_cases",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
