# Generated by Django 5.0.3 on 2024-04-02 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CaseForm",
        ),
    ]
