# Generated by Django 5.0.3 on 2024-03-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_lawyer_successful_cases_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
