# Generated by Django 4.2.11 on 2024-04-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_client_user_alter_lawyer_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="case_closed_successfully",
            field=models.BooleanField(default=False),
        ),
    ]
