# Generated by Django 4.2.11 on 2024-04-23 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_alter_case_case_closed_successfully'),
    ]

    operations = [

        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('cases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='app.case')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='app.client')),
                ('lawyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='app.lawyer')),
            ],
        ),
    ]
