# Generated by Django 4.2.11 on 2024-04-23 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_rename_cases_feedback_case_alter_client_user_and_more'),
    ]

    operations = [

        migrations.AlterField(
            model_name='feedback',
            name='case',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='app.case'),
        ),

    ]
